vim.lsp.config(
    "gopls", {
    cmd = { "gopls" },
    filetypes = { "go", "gomod", "gowork", "gompl" },
    root_markers = { "go.mod", "go.work", ".git" },
    settings = {
        gopls = {
            staticcheck = true,
            analyses = {
                -- correctness
                appends = true,
                asmdecl = true,
                assign = true,
                atomic = true,
                atomicalign = true,
                bools = true,
                buildtag = true,
                cgocall = true,
                composites = true,
                copylocks = true,
                deepequalerrors = true,
                defers = true,
                deprecated = true,
                directive = true,
                errorsas = true,
                framepointer = true,
                httpresponse = true,
                ifaceassert = true,
                infertypeargs = true,
                loopclosure = true,
                lostcancel = true,
                nilfunc = true,
                nilness = true,
                printf = true,
                shift = true,
                sigchanyzer = true,
                slog = true,
                stdmethods = true,
                stdversion = true,
                stringintconv = true,
                structtag = true,
                testinggoroutine = true,
                tests = true,
                timeformat = true,
                unmarshal = true,
                unreachable = true,
                unsafeptr = true,
                unusedresult = true,
                -- style / best practices
                unusedParams = true,
                unusedWrite = true,
                useany = true,
                waitgroup = true,
                hostport = true,
                loggercheck = true,
                -- fieldalignment reports struct field layout suggestions
                fieldalignment = false,
                -- shadow warns on shadowed variables (noisy, off by default)
                shadow = false,
            },
            hints = {
                assignVariableTypes = true,
                compositeLiteralFields = true,
                compositeLiteralTypes = true,
                constantValues = true,
                functionTypeParameters = true,
                parameterNames = true,
                rangeVariableTypes = true,
            },
            codelenses = {
                gc_details = true,
                generate = true,
                regenerate_cgo = true,
                run_govulncheck = true,
                test = true,
                tidy = true,
                upgrade_dependency = true,
                vendor = true,
            },
            usePlaceholders = true,
            completeUnimported = true,
            gofumpt = true,
            semanticTokens = true,
            vulncheck = "Imports",
            directoryFilters = { "-.git", "-.vscode", "-.idea", "-node_modules" },
        },
    },
})

vim.lsp.enable(
    "gopls"
)
